### ISSUE TITLE
id тоже должен быть

### ISSUE THREAD

**Issue by coursar** [FRahimov84/McDonald-s#1]
https://github.com/FRahimov84/McDonald-s/blob/3bf125467aef01de64f349e1bd34657094f1e7c6/schema.sql#L26

**Comment by FRahimov84** [comment]
зачем? 
нам надо только хранить кто что продал зачем им давать ID?
принципе он не нужен, нет?

**Comment by coursar** [comment]
Вам будет проще работать - выбирая конкретную продажу по id.
